// Created by Crowbar 0.74

// Stored modelname (without quotes): "C:\Documents and Settings\Andreas\Desktop\gruntammo\hornet.mdl"
$modelname "hornet.mdl"

$model "studio" "lolboll"

$surfaceprop "weapon"

$contents "solid"

$cdmaterials "models\vj_cofr\aom\eyeball\"

$illumposition 0 0 0 "Bone04"

$cbox 0 0 0 0 0 0

$bbox -8 -8 0 8 8 5

$hbox 0 "Bone04" -7.09 -1.9 -0.6008 2.88 2.28 0.6323

$sequence "idle" {
	"hornet_anims\idle"
	fps 30
	loop
}
